jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - template: job-steps.yml

- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: job-steps.yml

- job: macOS
  pool:
    vmImage: macOS-latest
  steps:
  - template: job-steps.yml

trigger:
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

schedules:
- cron: "0 11 * * *"
  displayName: Nightly at 4:00 PT
  always: false # Run only when there are code changes
  branches:
    include:
    - master
